### ISSUE TITLE
Use in Repeater Field

### ISSUE THREAD

**Issue by kimruddock** [paper-leaf/waldo#3]
I've tried using this in a template include which works fine for an image field in a field group. However when I've tried using in another include where the image field is output within a repeater field no styles are generated. The $waldo_styles variable creates and stores the styles but by the time the compile method runs on the wp_footer action $waldo_styles is empty.

**Comment by peterwegren** [comment]
Hey @kimruddock!

1. To clarify, `$waldo_styles` has all of the appropriate data stored _prior_ to the compile method, but is completely empty when/after the function is called?
2. Are you using a unique section/class name for each iteration over the repeater field?
3. Have you ruled out the potential issue of variable scope?
    >**Note:** WordPress does not allow implicit global variable access within some files (**header.php**, **footer.php**, and some template/include files). In these cases, the global Waldo variables may need to be explicitly declared at the beginning of the file in question.
